version: "3.9"
networks:
  default:
    external: true
    name: alphaLayer
    driver: bridge
services:
#  product:
#    build: 
#      context: ./ChoicesRemake/
#      dockerfile: "/Products/Dockerfile"
#    ports:
#      - "8000:80"
#      - "8001:443"
#    depends_on:
#      - db
  db:
    user: mssql
    volumes:
      - ./data:/var/opt/mssql/data
    build: "/ChoicesRemake/ProductsDBLayer/"
    ports:
      - "1433:1433"
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    container_name: zookeeper
    mem_limit: 512M
    mem_reservation: 256M
    cpus: 0.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:6.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    mem_limit: 1024m
    mem_reservation: 256M
    cpus: 0.5
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: -Xmx1024M -Xms256M
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: "alphaKafkaLayer:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    # 
    #  KAFKA_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092
    #  KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092
    #  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
    #  KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      #
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

