version: "3.9"
networks:
  default:
    external: true
    name: alphaLayer
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.23.0.0/16
#When ready for prod, remove external: true and uncomment driver and ipam sections above. Also uncomment the .net images and give them network.
services:
#  product:
#    build: 
#      context: ./ChoicesRemake/
#      dockerfile: "/Products/Dockerfile"
#    ports:
#      - "8000:80"
#      - "8001:443"
#    depends_on:
#      - db
#  auth:
#    build: 
#      context: ./ChoicesRemake/
#      dockerfile: "/Authorization/Dockerfile"
#    ports:
#      - "8000:80"
#      - "8001:443"
#    depends_on:
#      - broker
#      - authorizationdb
  productsdb:
    user: mssql
    volumes:
      - ./ChoicesRemake/ProductsDBLayer/SQLData:/var/opt/mssql/data
    build: "/ChoicesRemake/ProductsDBLayer/"
    ports:
      - "10420:1433"
    mem_limit: 1.5G
    networks:
      default:
        ipv4_address: 172.23.0.50
  authenticationdb:
    user: mssql
    volumes:
      - ./ChoicesRemake/AuthenticationIdentityDB/SQLData:/var/opt/mssql/data
    build: "/ChoicesRemake/AuthenticationIdentityDB/"
    ports:
      - "10421:1433"
    mem_limit: 1.5G
    networks:
      default:
        ipv4_address: 172.23.0.51
  authorizationdb:
    user: mssql
    volumes:
      - ./ChoicesRemake/AuthorizationDBLayer/SQLData:/var/opt/mssql/data
    build: "/ChoicesRemake/AuthorizationDBLayer/"
    ports:
      - "10422:1433"
    mem_limit: 1.5G
    networks:
      default:
        ipv4_address: 172.23.0.52
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    hostname: zookeeper
    container_name: zookeeper
    mem_limit: 512M
    cpus: 0.3
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_LOG_RETENTION_MS: 60000
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 30000
    networks:
      default:
        ipv4_address: 172.23.0.53
  rest-proxy:
    image: confluentinc/cp-kafka-rest:6.2.1
    depends_on:
      - broker
    ports:
      - 8082:8082
    hostname: rest-proxy
    mem_limit: 256M
    cpus: 0.2
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
      KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
    networks:
      default:
        ipv4_address: 172.23.0.54

  broker:
    image: confluentinc/cp-server:6.2.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    networks:
      default:
        ipv4_address: 172.23.0.55
    mem_limit: 1024M
    mem_reservation: 256M
    cpus: 0.5
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_HEAP_OPTS: -Xmx1024M -Xms256M
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    # 
    #  KAFKA_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092
    #  KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://broker:29092,LISTENER_FRED://localhost:9092
    #  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
    #  KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_BOB
      #

